name: Production Publish

on:
    push:
        branches: ['master']

env:
    REGISTRY: ${{ secrets.DOCKERREG_URL }}
    IMAGE_NAME: cart-khane-api:${{ github.sha }}

jobs:
    publish:
        name: Publish Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Login
              run: |
                  echo ${{ secrets.DOCKERREG_PASSWORD }} | docker login ${{ env.REGISTRY }} -u ${{ secrets.DOCKERREG_USERNAME }} --password-stdin
            - name: Build and Publish
              run: |
                  docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .
                  docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
